# site settings
title: Opencast
subtitle: Formations
email: stephane@libre-a-toi.org
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
auteur: Stéphane Manet
adresse: 22, rue Bernard Dimey
ville: Paris
code_postal: 75018
pays: France
phone: 06 51 51 19 40

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# contact form settings
form_url: https://formspree.io/stephane@libre-a-toi.org # endpoint URL to receive contact form submissions
form_email_name: _replyto # value of the "name" attribute in the "email" field

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://git.libre-a-toi.org/lat-formations
googleplus_url: https://plus.google.com/
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com
pinterest_url:
slack_url:
twitter_url: https://twitter.com/
messenger_url: https://messenger.com

# build settings
markdown: kramdown

sass:
  style: compressed
